---
output: pdf_document
---
\pagenumbering{gobble}

## Table 1. Description of fieldwork predictions

Predictions are identified ("predict id") in support of various relevant hypotheses and a plainly stated prediction, based largely on binary and categorical data from structured surveys (phase 1) and competence scores (phase 2). For brevity, we use the notational format "$X \sim Y$" to abbreviate, "$X$ is associated with $Y$". Specified support criteria for each prediction is listed in table 2.

\begin{center}
\def\arraystretch{1.25}%
  \begin{tabular}{l l l}
  \hline
  \textbf{predict id} & \textbf{relevant hypotheses} & \textbf{prediction} \\ [0.5 ex]
  \hline
  1 & i & laibon prophets $\sim$ social conflict (SC) \\
  
  2 & i&science advisors $\sim$ economic challenges (EC) \\
  
  3 &i,ii& each local expert $\sim$ unique problem domains (U)  \\
  4 & i,ii&overlapping problem domains (O) $\sim$ high conflict, low consensus  \\

  5 &i,ii &science advisors (agricultural sciences) $\sim$ low herd size (TLU) \\
  6 &i,ii &science advisors (medicine) $\sim$ novel diseases (ND)  \\
  7 &i,ii &science advisors (medicine) $\sim$ access to medicine  \\
  8 &i,ii &laibon healers $\sim$ common diseases (CD)  \\
  9 &i,ii &laibon healers $\sim$ low access to medicine \\
  
  10 & ii &individual trust in experts $\sim$ local consensus (neighbors) about trust \\
  11 & ii&each expert is highly important in trust network  \\
  12 &i,iii& laibon healers $\sim$ plant knowledge (PK)  \\
  13 &i,iii &expert problem domains $\sim$ high knowledge in problem domain \\
  \end{tabular}
\end{center}

